function lookmcxyz(name)
%
%   Displays the tissue cube, an overview over the optical and thermal
%   properties of the tissue types, and the output of the Monte Carlo
%   simulation. This file is called automatically by runMonteCarlo.m.
%
%   Input
%       name
%           the basename of the file generated by runMonteCarlo
%
%   Displays
%       Tissue cube
%       Tissue optical and thermal properties
%       Fluence rate
%       Absorbed power
%
%   Requires
%       plotVolumetric.m
%       plotTissueProperties.m
%

%% Updates
%   2014-08: Steven L. Jacques
%   2017-02: Steven L. Jacques
%   2017-06: Anders K. Hansen & Dominik Marti, DTU Fotonik, June 2017

%% Load data from makeTissue.m and MonteCarlo.m
load(['./Data/' name '.mat']);
load(['./Data/' name '_MCoutput.mat'],'F');

%% Make tissue plot
figure(1);
plotVolumetric(x,y,z,T,tissueList);
title('Tissue type illustration');
drawnow;

%% Make tissue properties plot
figure(7);clf;
plotTissueProperties(tissueList);
drawnow;

%% Make fluence rate plot
figure(2);
plotVolumetric(x,y,z,F);
title('Fluence rate (Intensity) [W/cm^2/W.incident] ')
drawnow;

%% Make power absorption plot
mua_vec = [tissueList.mua];
figure(3);
plotVolumetric(x,y,z,mua_vec(T).*F);
title('Normalized absorbed power per unit volume [W/cm^3/W.incident] ')
drawnow;

return
