function closeMCmatlabFigures()
allFigs = findall(groot,'type','figure');
for iF = 1:numel(allFigs)
    if ismember(allFigs(iF).Name,...
            {'Geometry illustration',...
            'Media properties',...
            'Normalized absorption',...
            'Normalized fluence rate',...
            'Photon paths',... % 5
            'Light collector illustration',...
            'Normalized fluence rate of collected incident light',...
            'Collected light',...
            'Far field',...
            'Normalized boundary irradiance',... % 10
            'Fluorescence emitters',...
            ...
            'Normalized fluorescence absorption',...
            'Normalized fluorescence fluence rate',...
            'Fluorescence photon paths',... % 15
            'Fluorescence light collector illustration',...
            'Normalized fluence rate of collected fluorescence light',...
            'Collected fluorescence light',...
            'Fluorescence far field',...
            'Normalized fluorescence boundary irradiance',... % 20
            'Temperature evolution',...
            ...
            'Temperature sensor illustration',...
            'Temperature sensor data',...
            'Thermal damage illustration',... % 25
            'Fractional damage',...
            'STL wireframes'})
        close(allFigs(iF));
    end
end
end
