function HC = Tissue_Prop_Matrix( T, s, TissueProps )
%Takes a matix containing medium types described by integers and returns a
%matrix containing e.g. the scattering coefficient at all points instead.
%   T is a matix containing integers descibing the types of tissue at each
%   point, s is the index of the property needed and TissueProps contain
%   the properties. 
%   This function is made for use with the 3D monte carlo code made by
%   Steven Jacques from Oregon Health & Science University and found at 
%   http://omlc.ogi.edu/software/mc/mcxyz/index.html - 07/01/2014
%   The T matrix and TissueProps are generated by the maketissue.m file
%   from his code.

for i=1:length(TissueProps(:,1))
    T(T==i)=TissueProps(i,s);
end
HC = T;
end

